const screens={splash:document.getElementById("splash"),language:document.getElementById("languageScreen"),permission:document.getElementById("permissionScreen"),app:document.getElementById("appScreen")};
const translations={fr:{title:"Choisir la langue",subtitle:"Faites glisser les drapeaux, puis continuez.",continue:"Continuer",gpsTitle:"Autoriser la localisation",gpsText:"OdyssAI utilise votre position pour afficher les activités proches de vous et organiser votre voyage.",gpsAllow:"Autoriser la localisation",gpsSkip:"Continuer sans GPS",waiting:"Position en attente...",noGps:"Mode test sans GPS",map:"Carte en direct · activités autour de vous",near:"Autour de vous",p1:"Restaurant bien noté",p1t:"À 450 m · estimé 22 €/personne",p2:"Lieu à visiter",p2t:"À 900 m · gratuit · 45 min",p3:"Pause café",p3t:"À 300 m · ouvert maintenant",see:"Voir",add:"Ajouter"},
he:{title:"בחר שפה",subtitle:"החליקו בין הדגלים ואז המשיכו.",continue:"המשך",gpsTitle:"אישור שימוש במיקום",gpsText:"OdyssAI משתמשת במיקום שלך כדי להציג פעילויות קרובות ולארגן את הטיול.",gpsAllow:"אשר מיקום",gpsSkip:"המשך בלי GPS",waiting:"ממתין למיקום...",noGps:"מצב בדיקה ללא GPS",map:"מפה חיה · פעילויות סביבך",near:"סביבך",p1:"מסעדה מומלצת",p1t:"450 מ׳ · כ־22 € לאדם",p2:"מקום לביקור",p2t:"900 מ׳ · חינם · 45 דקות",p3:"הפסקת קפה",p3t:"300 מ׳ · פתוח עכשיו",see:"הצג",add:"הוסף"},
en:{title:"Choose language",subtitle:"Swipe through the flags, then continue.",continue:"Continue",gpsTitle:"Allow location",gpsText:"OdyssAI uses your position to show nearby activities and organize your trip.",gpsAllow:"Allow location",gpsSkip:"Continue without GPS",waiting:"Waiting for position...",noGps:"Test mode without GPS",map:"Live map · nearby activities",near:"Around you",p1:"Highly rated restaurant",p1t:"450 m · estimated €22/person",p2:"Place to visit",p2t:"900 m · free · 45 min",p3:"Coffee break",p3t:"300 m · open now",see:"View",add:"Add"},
es:{title:"Elegir idioma",subtitle:"Desliza las banderas y continúa.",continue:"Continuar",gpsTitle:"Permitir ubicación",gpsText:"OdyssAI usa tu ubicación para mostrar actividades cercanas y organizar tu viaje.",gpsAllow:"Permitir ubicación",gpsSkip:"Continuar sin GPS",waiting:"Esperando ubicación...",noGps:"Modo prueba sin GPS",map:"Mapa en vivo · actividades cercanas",near:"Cerca de ti",p1:"Restaurante bien valorado",p1t:"A 450 m · estimado 22 €/persona",p2:"Lugar para visitar",p2t:"A 900 m · gratis · 45 min",p3:"Pausa café",p3t:"A 300 m · abierto ahora",see:"Ver",add:"Añadir"},
it:{title:"Scegli la lingua",subtitle:"Scorri le bandiere e continua.",continue:"Continua",gpsTitle:"Consenti posizione",gpsText:"OdyssAI usa la tua posizione per mostrare attività vicine e organizzare il viaggio.",gpsAllow:"Consenti posizione",gpsSkip:"Continua senza GPS",waiting:"In attesa della posizione...",noGps:"Modalità test senza GPS",map:"Mappa live · attività vicine",near:"Intorno a te",p1:"Ristorante ben valutato",p1t:"A 450 m · stimato 22 €/persona",p2:"Luogo da visitare",p2t:"A 900 m · gratis · 45 min",p3:"Pausa caffè",p3t:"A 300 m · aperto ora",see:"Vedi",add:"Aggiungi"},
de:{title:"Sprache wählen",subtitle:"Wischen Sie durch die Flaggen und fahren Sie fort.",continue:"Weiter",gpsTitle:"Standort erlauben",gpsText:"OdyssAI nutzt Ihren Standort, um Aktivitäten in der Nähe anzuzeigen und Ihre Reise zu organisieren.",gpsAllow:"Standort erlauben",gpsSkip:"Ohne GPS weiter",waiting:"Warte auf Standort...",noGps:"Testmodus ohne GPS",map:"Live-Karte · Aktivitäten in der Nähe",near:"In Ihrer Nähe",p1:"Gut bewertetes Restaurant",p1t:"450 m · ca. 22 €/Person",p2:"Sehenswürdigkeit",p2t:"900 m · kostenlos · 45 Min.",p3:"Kaffeepause",p3t:"300 m · jetzt geöffnet",see:"Ansehen",add:"Hinzufügen"}};
let selectedLang="fr";let carouselReady=false;const carousel=document.getElementById("languageCarousel");
function show(name){Object.values(screens).forEach(s=>s.classList.remove("active"));screens[name].classList.add("active");}
setTimeout(()=>{show("language");initCarouselLoop();},5800);
function applyLanguage(){const t=translations[selectedLang]||translations.fr;document.documentElement.lang=selectedLang;document.documentElement.dir=selectedLang==="he"?"rtl":"ltr";langTitle.textContent=t.title;langSubtitle.textContent=t.subtitle;continueBtn.textContent=t.continue;gpsTitle.textContent=t.gpsTitle;gpsText.textContent=t.gpsText;gpsAllowBtn.textContent=t.gpsAllow;gpsSkipBtn.textContent=t.gpsSkip;locationText.textContent=t.waiting;mapLabel.textContent=t.map;nearTitle.textContent=t.near;place1Title.textContent=t.p1;place1Text.textContent=t.p1t;place2Title.textContent=t.p2;place2Text.textContent=t.p2t;place3Title.textContent=t.p3;place3Text.textContent=t.p3t;place1Btn.textContent=t.see;place2Btn.textContent=t.add;place3Btn.textContent=t.see;}
function selectButton(button){document.querySelectorAll(".language").forEach(b=>b.classList.remove("selected"));button.classList.add("selected");selectedLang=button.dataset.lang;applyLanguage();}
document.querySelectorAll(".language").forEach(button=>button.addEventListener("click",()=>selectButton(button)));
function initCarouselLoop(){if(carouselReady)return;carouselReady=true;const originals=[...carousel.children];originals.forEach(el=>carousel.appendChild(el.cloneNode(true)));originals.slice().reverse().forEach(el=>carousel.insertBefore(el.cloneNode(true),carousel.firstChild));[...carousel.querySelectorAll(".language")].forEach(button=>button.addEventListener("click",()=>selectButton(button)));const card=186;carousel.scrollLeft=card*originals.length;selectButton([...carousel.querySelectorAll('.language')].find(b=>b.dataset.lang==="fr"));carousel.addEventListener("scroll",()=>{const max=carousel.scrollWidth-carousel.clientWidth;const segment=card*originals.length;if(carousel.scrollLeft<segment*.35){carousel.scrollLeft+=segment;}else if(carousel.scrollLeft>max-segment*.35){carousel.scrollLeft-=segment;}},{passive:true});}
function confirmLanguage(){show("permission");}
function requestLocation(){if(!navigator.geolocation){openApp(false);return;}navigator.geolocation.getCurrentPosition((position)=>{openApp(true,position.coords.latitude.toFixed(5),position.coords.longitude.toFixed(5));},()=>openApp(false),{enableHighAccuracy:true,timeout:7000,maximumAge:0});}
function openApp(hasGps,lat,lon){show("app");const t=translations[selectedLang]||translations.fr;locationText.textContent=hasGps?`GPS : ${lat}, ${lon}`:t.noGps;}
function restart(){show("language");setTimeout(initCarouselLoop,100);}